### ISSUE TITLE
esp32s3 crashed after enable usb_webcam

### ISSUE THREAD

**Issue by ffalsk** [anton-malakhov/esphome_webcam#1]
here is my yaml

```yaml
esphome:
  name: smart-door
  platformio_options:
    board_build.flash_mode: dio  # default mode is wrong
    board_build.f_cpu: 240000000L
    board_upload.maximum_ram_size: 8716288
    board_upload.maximum_size: 16777216
    # board_build.partitions: "config/esphome/custom_partitions.csv"

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

external_components:
  - source: github://anton-malakhov/esphome_webcam
  - source: github://trombik/esphome-component-ping
  - source: github://ayufan/esphome-components
  - source: github://dentra/esphome-components

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8LRI+SLJENFrXwgMTbgTCJCCJZb2j2RrhgE0bp0d/M4="

ota:
  - platform: esphome
    password: "be5ad274aa80576b19b12648a6d1222b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:

psram:
  mode: octal
  speed: 80MHz

# memory:

# usb_webcam:
#   name: usb-webcam
#   resolution: 800x600

backup:
  auth:
    username: !secret backup_username
    password: !secret backup_password

```
